@WiseUpDude_HostAddress = https://localhost:7150

GET {{WiseUpDude_HostAddress}}/api/specialquizassignments/types

###

GET {{WiseUpDude_HostAddress}}/api/specialquizassignments

###

GET {{WiseUpDude_HostAddress}}/api/specialquizassignments

###
